/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Frame;

/**
 *
 * @author LAPTOPTOKYO
 */
public class FrameDemo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrameDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Frame = new javax.swing.JPanel();
        lbl_Close = new javax.swing.JLabel();
        lbl_Hiden = new javax.swing.JLabel();
        lbl_Header = new javax.swing.JLabel();
        sp_Menu = new javax.swing.JScrollPane();
        pn_Menu = new javax.swing.JPanel();
        lbl_MenuBanHang = new javax.swing.JLabel();
        lbl_NhapHang = new javax.swing.JLabel();
        lbl_NhanVien = new javax.swing.JLabel();
        lbl_KhachHang = new javax.swing.JLabel();
        jlbMon = new javax.swing.JLabel();
        jlbLuong = new javax.swing.JLabel();
        jlbNhaCungCap = new javax.swing.JLabel();
        jlbKhuyenMai = new javax.swing.JLabel();
        jlbUuDai = new javax.swing.JLabel();
        jlbChucVu = new javax.swing.JLabel();
        jlbTaiKhoan = new javax.swing.JLabel();
        jlbQuanLyApp = new javax.swing.JLabel();
        jlbTinhThue = new javax.swing.JLabel();
        jlbTKBanHang = new javax.swing.JLabel();
        jlbTKChiTra = new javax.swing.JLabel();
        jlbTKDoanhThu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pn_Frame.setBackground(new java.awt.Color(255, 255, 255));
        pn_Frame.setPreferredSize(new java.awt.Dimension(1920, 1050));
        pn_Frame.setLayout(null);

        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close1.png"))); // NOI18N
        lbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_CloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseReleased(evt);
            }
        });
        pn_Frame.add(lbl_Close);
        lbl_Close.setBounds(1880, 5, 40, 40);

        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an1.png"))); // NOI18N
        lbl_Hiden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_HidenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseReleased(evt);
            }
        });
        pn_Frame.add(lbl_Hiden);
        lbl_Hiden.setBounds(1835, 5, 40, 40);

        lbl_Header.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Header.setOpaque(true);
        pn_Frame.add(lbl_Header);
        lbl_Header.setBounds(-220, 0, 2140, 50);

        sp_Menu.setBackground(new java.awt.Color(0, 0, 0));
        sp_Menu.setBorder(null);
        sp_Menu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sp_Menu.setToolTipText("");
        sp_Menu.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sp_Menu.setPreferredSize(new java.awt.Dimension(198, 800));

        pn_Menu.setBackground(new java.awt.Color(0, 0, 0));
        pn_Menu.setPreferredSize(new java.awt.Dimension(198, 1200));
        pn_Menu.setLayout(null);

        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang1.png"))); // NOI18N
        lbl_MenuBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_MenuBanHang);
        lbl_MenuBanHang.setBounds(0, 0, 200, 70);

        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang1.png"))); // NOI18N
        lbl_NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_NhapHang);
        lbl_NhapHang.setBounds(0, 70, 200, 70);

        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien1.png"))); // NOI18N
        lbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_NhanVien);
        lbl_NhanVien.setBounds(0, 140, 200, 70);

        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang1.png"))); // NOI18N
        lbl_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_KhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_KhachHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_KhachHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_KhachHangMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_KhachHang);
        lbl_KhachHang.setBounds(0, 210, 200, 70);

        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon1.png"))); // NOI18N
        jlbMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbMonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbMonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbMonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbMonMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbMon);
        jlbMon.setBounds(0, 280, 200, 70);

        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong1.png"))); // NOI18N
        jlbLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbLuongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbLuongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbLuongMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbLuong);
        jlbLuong.setBounds(0, 350, 200, 70);

        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap1.png"))); // NOI18N
        jlbNhaCungCap.setToolTipText("");
        jlbNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbNhaCungCap);
        jlbNhaCungCap.setBounds(0, 420, 200, 70);

        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai1.png"))); // NOI18N
        jlbKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbKhuyenMai);
        jlbKhuyenMai.setBounds(0, 490, 200, 70);

        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai1.png"))); // NOI18N
        jlbUuDai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbUuDaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbUuDai);
        jlbUuDai.setBounds(0, 560, 200, 70);

        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu1.png"))); // NOI18N
        jlbChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbChucVuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbChucVu);
        jlbChucVu.setBounds(0, 630, 200, 70);

        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan1.png"))); // NOI18N
        jlbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbTaiKhoan);
        jlbTaiKhoan.setBounds(0, 700, 200, 70);

        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp1.png"))); // NOI18N
        jlbQuanLyApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbQuanLyApp);
        jlbQuanLyApp.setBounds(0, 770, 200, 70);

        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue1.png"))); // NOI18N
        jlbTinhThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTinhThueMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbTinhThue);
        jlbTinhThue.setBounds(0, 840, 200, 70);

        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang1.png"))); // NOI18N
        jlbTKBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbTKBanHang);
        jlbTKBanHang.setBounds(0, 910, 200, 70);

        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra1.png"))); // NOI18N
        jlbTKChiTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbTKChiTra);
        jlbTKChiTra.setBounds(0, 980, 200, 70);

        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu1.png"))); // NOI18N
        jlbTKDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseReleased(evt);
            }
        });
        pn_Menu.add(jlbTKDoanhThu);
        jlbTKDoanhThu.setBounds(0, 1050, 200, 70);

        sp_Menu.setViewportView(pn_Menu);

        pn_Frame.add(sp_Menu);
        sp_Menu.setBounds(0, 50, 220, 1000);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        pn_Frame.add(jLabel2);
        jLabel2.setBounds(0, 0, 200, 1050);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Set onclick cho jlbClose(Đóng ứng dụng)
    private void lbl_CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseReleased
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMouseReleased

    private void lbl_CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMousePressed
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMousePressed

    private void lbl_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseEntered
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMouseEntered

    private void lbl_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseExited
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMouseExited

    private void lbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_CloseMouseClicked
    
    //Set onclick cho jlbHiden(Ẩn xuống thanh tabkbar)
    private void lbl_HidenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseReleased
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMouseReleased

    private void lbl_HidenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMousePressed
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMousePressed

    private void lbl_HidenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseEntered
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMouseEntered

    private void lbl_HidenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseExited
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMouseExited

    private void lbl_HidenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lbl_HidenMouseClicked

    //Set onclick cho jlbMenuBanHang
    private void lbl_MenuBanHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseReleased
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMouseReleased

    private void lbl_MenuBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMousePressed
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMousePressed

    private void lbl_MenuBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseExited
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMouseExited

    private void lbl_MenuBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseEntered
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMouseEntered

    private void lbl_MenuBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_MenuBanHangMouseClicked
    
    //Set onclick cho jlbBanHang
    private void lbl_NhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseClicked
        
    }//GEN-LAST:event_lbl_NhapHangMouseClicked

    private void lbl_NhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseEntered
       lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapHangMouseEntered

    private void lbl_NhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseExited
        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapHangMouseExited

    private void lbl_NhapHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMousePressed
        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapHangMousePressed

    private void lbl_NhapHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseReleased
        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapHangMouseReleased
    
    //Set onclick cho jlbNhanVien
    private void lbl_NhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseReleased
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMouseReleased

    private void lbl_NhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMousePressed
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMousePressed

    private void lbl_NhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseEntered
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMouseEntered

    private void lbl_NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseExited
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMouseExited
    
    private void lbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_NhanVienMouseClicked
    
    //Set onclick cho jlbKhachHang
    private void lbl_KhachHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhachHangMouseReleased
        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_KhachHangMouseReleased

    private void lbl_KhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhachHangMousePressed
        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_KhachHangMousePressed

    private void lbl_KhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhachHangMouseEntered
        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_KhachHangMouseEntered

    private void lbl_KhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhachHangMouseExited
        lbl_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_KhachHangMouseExited

    private void lbl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhachHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_KhachHangMouseClicked
    
    //Set onclick cho jlbMon
    private void jlbMonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseReleased
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMouseReleased

    private void jlbMonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMousePressed
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMousePressed

    private void jlbMonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseEntered
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMouseEntered

    private void jlbMonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseExited
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon1.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMouseExited

    private void jlbMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbMonMouseClicked
    
    //Set onclick cho jlbLuong
    private void jlbLuongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseReleased
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong2.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMouseReleased

    private void jlbLuongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMousePressed
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong2.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMousePressed

    private void jlbLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseEntered
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong2.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMouseEntered

    private void jlbLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseExited
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong1.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMouseExited

    private void jlbLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbLuongMouseClicked
    
    //Set onclick cho jlbNhaCungCap
    private void jlbNhaCungCapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseReleased
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseReleased

    private void jlbNhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMousePressed
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMousePressed

    private void jlbNhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseEntered
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseEntered

    private void jlbNhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseExited
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap1.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseExited

    private void jlbNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbNhaCungCapMouseClicked
    
    //Set onclick cho jlbKhuyenMai
    private void jlbKhuyenMaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseReleased
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMouseReleased

    private void jlbKhuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMousePressed
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMousePressed

    private void jlbKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseEntered
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMouseEntered

    private void jlbKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseExited
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai1.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMouseExited

    private void jlbKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbKhuyenMaiMouseClicked
    
    //Set onclick cho jlbUuDai
    private void jlbUuDaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseReleased
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMouseReleased

    private void jlbUuDaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMousePressed
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMousePressed

    private void jlbUuDaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseEntered
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMouseEntered

    private void jlbUuDaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseExited
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai1.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMouseExited

    private void jlbUuDaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbUuDaiMouseClicked
    
    //Set onclick cho jlbChucVu
    private void jlbChucVuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseReleased
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseReleased

    private void jlbChucVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMousePressed
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMousePressed

    private void jlbChucVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseEntered
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseEntered

    private void jlbChucVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseExited
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu1.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseExited

    private void jlbChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbChucVuMouseClicked
    
    //Set onclick cho jlbTaiKhoan
    private void jlbTaiKhoanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseReleased
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMouseReleased

    private void jlbTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMousePressed
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMousePressed

    private void jlbTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseEntered
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMouseEntered

    private void jlbTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseExited
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMouseExited

    private void jlbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTaiKhoanMouseClicked
    
    //Set onclick cho jlbQuanLyApp
    private void jlbQuanLyAppMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseReleased
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp2.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMouseReleased

    private void jlbQuanLyAppMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMousePressed
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp2.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMousePressed

    private void jlbQuanLyAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseEntered
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp2.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMouseEntered

    private void jlbQuanLyAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseExited
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp1.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMouseExited

    private void jlbQuanLyAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbQuanLyAppMouseClicked
    
    //Set onclick cho jlbTinhThue
    private void jlbTinhThueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseReleased
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMouseReleased

    private void jlbTinhThueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMousePressed
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMousePressed

    private void jlbTinhThueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseEntered
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMouseEntered

    private void jlbTinhThueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseExited
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMouseExited

    private void jlbTinhThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTinhThueMouseClicked
    
    //Set onclick cho jlbTKBanHang
    private void jlbTKBanHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseReleased
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMouseReleased

    private void jlbTKBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMousePressed
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMousePressed

    private void jlbTKBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseEntered
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMouseEntered

    private void jlbTKBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseExited
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMouseExited

    private void jlbTKBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTKBanHangMouseClicked
    
    //Set onclick cho jlbTKBanHang
    private void jlbTKChiTraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseReleased
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMouseReleased

    private void jlbTKChiTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMousePressed
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMousePressed

    private void jlbTKChiTraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseEntered
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMouseEntered

    private void jlbTKChiTraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseExited
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMouseExited

    private void jlbTKChiTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTKChiTraMouseClicked
    
    //Set onclick cho jlbTKDoanhThu
    private void jlbTKDoanhThuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseReleased
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMouseReleased

    private void jlbTKDoanhThuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMousePressed
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMousePressed

    private void jlbTKDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseEntered
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMouseEntered

    private void jlbTKDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseExited
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMouseExited

    private void jlbTKDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTKDoanhThuMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbChucVu;
    private javax.swing.JLabel jlbKhuyenMai;
    private javax.swing.JLabel jlbLuong;
    private javax.swing.JLabel jlbMon;
    private javax.swing.JLabel jlbNhaCungCap;
    private javax.swing.JLabel jlbQuanLyApp;
    private javax.swing.JLabel jlbTKBanHang;
    private javax.swing.JLabel jlbTKChiTra;
    private javax.swing.JLabel jlbTKDoanhThu;
    private javax.swing.JLabel jlbTaiKhoan;
    private javax.swing.JLabel jlbTinhThue;
    private javax.swing.JLabel jlbUuDai;
    private javax.swing.JLabel lbl_Close;
    private javax.swing.JLabel lbl_Header;
    private javax.swing.JLabel lbl_Hiden;
    private javax.swing.JLabel lbl_KhachHang;
    private javax.swing.JLabel lbl_MenuBanHang;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_NhapHang;
    private javax.swing.JPanel pn_Frame;
    private javax.swing.JPanel pn_Menu;
    private javax.swing.JScrollPane sp_Menu;
    // End of variables declaration//GEN-END:variables
}
