/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Frame;
import javax.swing.ImageIcon;

/**
 *
 * @author LAPTOPTOKYO
 */
public class FrameMenu extends javax.swing.JFrame {
    private String strMaNV,strTenNV,strChucVu;
    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
    }
    public FrameMenu(String strMaNV,String strTenNV,String strChucVu) {
        initComponents();
        this.strMaNV=strMaNV;
        this.strTenNV=strTenNV;
        this.strChucVu=strChucVu;
        jlbTenNhanVien2.setText(strTenNV);
        jlbChucVu2.setText(strChucVu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jlbMenuBanHang = new javax.swing.JLabel();
        jlbNhapHang = new javax.swing.JLabel();
        jlbNhanVien = new javax.swing.JLabel();
        jlbKhahcHang = new javax.swing.JLabel();
        jlbMon = new javax.swing.JLabel();
        jlbKho = new javax.swing.JLabel();
        jlbQuanLyLuong = new javax.swing.JLabel();
        jlbChucVu = new javax.swing.JLabel();
        jlbQLKhuyenMai = new javax.swing.JLabel();
        jlbNhaCungCap = new javax.swing.JLabel();
        jlbUuDaiThanhVien = new javax.swing.JLabel();
        jlbQLCaLam = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlbClose = new javax.swing.JLabel();
        jlbHiden = new javax.swing.JLabel();
        jlbHeader = new javax.swing.JLabel();
        jlbTenNhanVien1 = new javax.swing.JLabel();
        jlbTenNhanVien2 = new javax.swing.JLabel();
        jlbChucVu1 = new javax.swing.JLabel();
        jlbChucVu2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý cà phê");
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1050));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1050));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1801, 1000));
        jPanel2.setLayout(null);

        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang1.jpg"))); // NOI18N
        jlbMenuBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseReleased(evt);
            }
        });
        jPanel2.add(jlbMenuBanHang);
        jlbMenuBanHang.setBounds(0, 0, 400, 203);

        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang1.jpg"))); // NOI18N
        jlbNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbNhapHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseReleased(evt);
            }
        });
        jPanel2.add(jlbNhapHang);
        jlbNhapHang.setBounds(464, 0, 400, 200);

        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien1.jpg"))); // NOI18N
        jlbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbNhanVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseReleased(evt);
            }
        });
        jPanel2.add(jlbNhanVien);
        jlbNhanVien.setBounds(928, 0, 400, 200);

        jlbKhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang1.jpg"))); // NOI18N
        jlbKhahcHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbKhahcHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbKhahcHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbKhahcHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbKhahcHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbKhahcHangMouseReleased(evt);
            }
        });
        jPanel2.add(jlbKhahcHang);
        jlbKhahcHang.setBounds(1392, 0, 400, 200);

        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon1.jpg"))); // NOI18N
        jlbMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbMonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbMonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbMonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbMonMouseReleased(evt);
            }
        });
        jPanel2.add(jlbMon);
        jlbMon.setBounds(0, 230, 400, 200);

        jlbKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho1.jpg"))); // NOI18N
        jlbKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbKhoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbKhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbKhoMouseReleased(evt);
            }
        });
        jPanel2.add(jlbKho);
        jlbKho.setBounds(464, 230, 400, 200);

        jlbQuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong1.jpg"))); // NOI18N
        jlbQuanLyLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbQuanLyLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbQuanLyLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbQuanLyLuongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbQuanLyLuongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbQuanLyLuongMouseReleased(evt);
            }
        });
        jPanel2.add(jlbQuanLyLuong);
        jlbQuanLyLuong.setBounds(1392, 230, 400, 200);

        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu1.jpg"))); // NOI18N
        jlbChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbChucVuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseReleased(evt);
            }
        });
        jPanel2.add(jlbChucVu);
        jlbChucVu.setBounds(928, 230, 400, 200);

        jlbQLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai1.jpg"))); // NOI18N
        jlbQLKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbQLKhuyenMaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbQLKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbQLKhuyenMaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbQLKhuyenMaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbQLKhuyenMaiMouseReleased(evt);
            }
        });
        jPanel2.add(jlbQLKhuyenMai);
        jlbQLKhuyenMai.setBounds(0, 460, 400, 200);

        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap1.jpg"))); // NOI18N
        jlbNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseReleased(evt);
            }
        });
        jPanel2.add(jlbNhaCungCap);
        jlbNhaCungCap.setBounds(464, 460, 400, 200);

        jlbUuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien1.jpg"))); // NOI18N
        jlbUuDaiThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbUuDaiThanhVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbUuDaiThanhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbUuDaiThanhVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbUuDaiThanhVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbUuDaiThanhVienMouseReleased(evt);
            }
        });
        jPanel2.add(jlbUuDaiThanhVien);
        jlbUuDaiThanhVien.setBounds(928, 460, 400, 200);

        jlbQLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam1.jpg"))); // NOI18N
        jlbQLCaLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbQLCaLamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbQLCaLamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbQLCaLamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbQLCaLamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbQLCaLamMouseReleased(evt);
            }
        });
        jPanel2.add(jlbQLCaLam);
        jlbQLCaLam.setBounds(1392, 460, 400, 200);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke1.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, 690, 400, 200);

        jScrollPane2.setViewportView(jPanel2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 400, 1820, 600);

        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close1.png"))); // NOI18N
        jlbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbCloseMouseReleased(evt);
            }
        });
        jPanel1.add(jlbClose);
        jlbClose.setBounds(1880, 5, 40, 40);

        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an1.png"))); // NOI18N
        jlbHiden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHidenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbHidenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbHidenMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbHidenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbHidenMouseReleased(evt);
            }
        });
        jPanel1.add(jlbHiden);
        jlbHiden.setBounds(1835, 5, 40, 40);

        jlbHeader.setBackground(new java.awt.Color(0, 0, 0));
        jlbHeader.setOpaque(true);
        jPanel1.add(jlbHeader);
        jlbHeader.setBounds(0, 0, 1920, 50);

        jlbTenNhanVien1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlbTenNhanVien1.setText("Tên nhân viên:");
        jPanel1.add(jlbTenNhanVien1);
        jlbTenNhanVien1.setBounds(120, 120, 230, 60);

        jlbTenNhanVien2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jPanel1.add(jlbTenNhanVien2);
        jlbTenNhanVien2.setBounds(360, 120, 500, 60);

        jlbChucVu1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlbChucVu1.setText("Chức vụ:");
        jPanel1.add(jlbChucVu1);
        jlbChucVu1.setBounds(120, 190, 150, 60);

        jlbChucVu2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jPanel1.add(jlbChucVu2);
        jlbChucVu2.setBounds(270, 190, 300, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1920, 1050);
    }// </editor-fold>//GEN-END:initComponents
    
    //Icon để setIcon khi hover vào menu bán hàng 
    private void jlbMenuBanHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseReleased
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMouseReleased

    private void jlbMenuBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMousePressed
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMousePressed

    private void jlbMenuBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseEntered
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMouseEntered

    private void jlbMenuBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseExited
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMouseExited

    private void jlbMenuBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbMenuBanHangMouseClicked
    
   
    //Icon để setIcon khi hover vào nhân viên
    private void jlbNhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseReleased
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMouseReleased

    private void jlbNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMousePressed
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMousePressed

    private void jlbNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseEntered
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMouseEntered

    private void jlbNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseExited
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMouseExited

    private void jlbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbNhanVienMouseClicked
    
    //Icon để setIcon khi hover vào khách hàng
    private void jlbKhahcHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhahcHangMouseReleased
        jlbKhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhahcHangMouseReleased

    private void jlbKhahcHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhahcHangMousePressed
        jlbKhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang12.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhahcHangMousePressed

    private void jlbKhahcHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhahcHangMouseEntered
        jlbKhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhahcHangMouseEntered

    private void jlbKhahcHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhahcHangMouseExited
        jlbKhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhahcHangMouseExited

    private void jlbKhahcHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhahcHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbKhahcHangMouseClicked
    
    //Icon để setIcon khi hover vào món
    private void jlbMonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseReleased
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon2.jpg")));// NOI18N
    }//GEN-LAST:event_jlbMonMouseReleased

    private void jlbMonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMousePressed
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon2.jpg")));// NOI18N
    }//GEN-LAST:event_jlbMonMousePressed

    private void jlbMonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseEntered
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon2.jpg")));// NOI18N
    }//GEN-LAST:event_jlbMonMouseEntered

    private void jlbMonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseExited
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbMonMouseExited

    private void jlbMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlbMonMouseClicked
    
    //Icon để setIcon khi hover vào kho
    private void jlbKhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhoMouseReleased
        jlbKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhoMouseReleased

    private void jlbKhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhoMousePressed
        jlbKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhoMousePressed

    private void jlbKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhoMouseEntered
        jlbKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhoMouseEntered

    private void jlbKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhoMouseExited
        jlbKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbKhoMouseExited

    private void jlbKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbKhoMouseClicked
    
    //Icon để setIcon khi hover vào nhập hàng
    private void jlbNhapHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseReleased
        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang2.jpg"))); // NOI18N                                   
    }//GEN-LAST:event_jlbNhapHangMouseReleased

    private void jlbNhapHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMousePressed
        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang2.jpg"))); // NOI18N                                  
    }//GEN-LAST:event_jlbNhapHangMousePressed

    private void jlbNhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseEntered
        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang2.jpg"))); // NOI18N          
    }//GEN-LAST:event_jlbNhapHangMouseEntered

    private void jlbNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseExited
        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhapHangMouseExited

    private void jlbNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbNhapHangMouseClicked
    
    //Icon để setIcon khi hover vào quản lý lương
    private void jlbQuanLyLuongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyLuongMouseReleased
        jlbQuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyLuongMouseReleased

    private void jlbQuanLyLuongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyLuongMousePressed
        jlbQuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyLuongMousePressed

    private void jlbQuanLyLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyLuongMouseEntered
        jlbQuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyLuongMouseEntered

    private void jlbQuanLyLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyLuongMouseExited
        jlbQuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyLuongMouseExited

    private void jlbQuanLyLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyLuongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbQuanLyLuongMouseClicked
    
    //Icon để setIcon khi hover vào chức vụ
    private void jlbChucVuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseReleased
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseReleased

    private void jlbChucVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMousePressed
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMousePressed

    private void jlbChucVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseEntered
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseEntered

    private void jlbChucVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseExited
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseExited

    private void jlbChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbChucVuMouseClicked
    
    //Icon để setIcon khi hover vào khuyến mãi
    private void jlbQLKhuyenMaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLKhuyenMaiMouseReleased
        jlbQLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLKhuyenMaiMouseReleased

    private void jlbQLKhuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLKhuyenMaiMousePressed
        jlbQLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLKhuyenMaiMousePressed

    private void jlbQLKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLKhuyenMaiMouseEntered
        jlbQLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLKhuyenMaiMouseEntered

    private void jlbQLKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLKhuyenMaiMouseExited
        jlbQLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLKhuyenMaiMouseExited

    private void jlbQLKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLKhuyenMaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbQLKhuyenMaiMouseClicked
    
    //Icon để setIcon khi hover vào nhà cung cấp
    private void jlbNhaCungCapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseReleased
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseReleased

    private void jlbNhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMousePressed
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMousePressed

    private void jlbNhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseEntered
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseEntered

    private void jlbNhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseExited
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseExited

    private void jlbNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbNhaCungCapMouseClicked
    
    //Icon để setIcon khi hover vào ưu đãi thành viên
    private void jlbUuDaiThanhVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiThanhVienMouseReleased
        jlbUuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiThanhVienMouseReleased

    private void jlbUuDaiThanhVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiThanhVienMousePressed
        jlbUuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiThanhVienMousePressed

    private void jlbUuDaiThanhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiThanhVienMouseEntered
        jlbUuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiThanhVienMouseEntered

    private void jlbUuDaiThanhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiThanhVienMouseExited
        jlbUuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiThanhVienMouseExited

    private void jlbUuDaiThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiThanhVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbUuDaiThanhVienMouseClicked
    
    //Icon để setIcon khi hover vào thống kê
    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke2.jpg"))); // NOI18N
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke2.jpg"))); // NOI18N
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke2.jpg"))); // NOI18N
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke1.jpg"))); // NOI18N
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    //Icon để setIcon khi hover vào ca làm
    private void jlbQLCaLamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLCaLamMouseReleased
        jlbQLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLCaLamMouseReleased

    private void jlbQLCaLamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLCaLamMousePressed
        jlbQLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLCaLamMousePressed

    private void jlbQLCaLamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLCaLamMouseExited
        jlbQLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam1.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLCaLamMouseExited

    private void jlbQLCaLamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLCaLamMouseEntered
        jlbQLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam2.jpg"))); // NOI18N
    }//GEN-LAST:event_jlbQLCaLamMouseEntered

    private void jlbQLCaLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQLCaLamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbQLCaLamMouseClicked
    
    //Icon để setIcon khi hover vào close
    private void jlbCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseReleased
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMouseReleased

    private void jlbCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMousePressed
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMousePressed

    private void jlbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseEntered
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMouseEntered

    private void jlbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseExited
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close1.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMouseExited

    private void jlbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlbCloseMouseClicked
    
    //Icon để setIcon khi hover vào hiden
    private void jlbHidenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseReleased
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMouseReleased

    private void jlbHidenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMousePressed
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMousePressed

    private void jlbHidenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseEntered
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMouseEntered

    private void jlbHidenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseExited
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an1.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMouseExited

    private void jlbHidenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jlbHidenMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbChucVu;
    private javax.swing.JLabel jlbChucVu1;
    private javax.swing.JLabel jlbChucVu2;
    private javax.swing.JLabel jlbClose;
    private javax.swing.JLabel jlbHeader;
    private javax.swing.JLabel jlbHiden;
    private javax.swing.JLabel jlbKhahcHang;
    private javax.swing.JLabel jlbKho;
    private javax.swing.JLabel jlbMenuBanHang;
    private javax.swing.JLabel jlbMon;
    private javax.swing.JLabel jlbNhaCungCap;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbNhapHang;
    private javax.swing.JLabel jlbQLCaLam;
    private javax.swing.JLabel jlbQLKhuyenMai;
    private javax.swing.JLabel jlbQuanLyLuong;
    private javax.swing.JLabel jlbTenNhanVien1;
    private javax.swing.JLabel jlbTenNhanVien2;
    private javax.swing.JLabel jlbUuDaiThanhVien;
    // End of variables declaration//GEN-END:variables
}
