/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Frame;

/**
 *
 * @author LAPTOPTOKYO
 */
public class FrameDemo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrameDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFrame = new javax.swing.JPanel();
        jlbClose = new javax.swing.JLabel();
        jlbHiden = new javax.swing.JLabel();
        jblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pScrollPane = new javax.swing.JPanel();
        jlbMenuBanHang = new javax.swing.JLabel();
        jlbNhapHang = new javax.swing.JLabel();
        jlbNhanVien = new javax.swing.JLabel();
        jlbKhachHang = new javax.swing.JLabel();
        jlbMon = new javax.swing.JLabel();
        jlbLuong = new javax.swing.JLabel();
        jlbNhaCungCap = new javax.swing.JLabel();
        jlbKhuyenMai = new javax.swing.JLabel();
        jlbUuDai = new javax.swing.JLabel();
        jlbChucVu = new javax.swing.JLabel();
        jlbTaiKhoan = new javax.swing.JLabel();
        jlbQuanLyApp = new javax.swing.JLabel();
        jlbTinhThue = new javax.swing.JLabel();
        jlbTKBanHang = new javax.swing.JLabel();
        jlbTKChiTra = new javax.swing.JLabel();
        jlbTKDoanhThu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pFrame.setBackground(new java.awt.Color(255, 255, 255));
        pFrame.setPreferredSize(new java.awt.Dimension(1920, 1050));
        pFrame.setLayout(null);

        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close1.png"))); // NOI18N
        jlbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbCloseMouseReleased(evt);
            }
        });
        pFrame.add(jlbClose);
        jlbClose.setBounds(1880, 5, 40, 40);

        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an1.png"))); // NOI18N
        jlbHiden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHidenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbHidenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbHidenMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbHidenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbHidenMouseReleased(evt);
            }
        });
        pFrame.add(jlbHiden);
        jlbHiden.setBounds(1835, 5, 40, 40);

        jblHeader.setBackground(new java.awt.Color(0, 0, 0));
        jblHeader.setOpaque(true);
        pFrame.add(jblHeader);
        jblHeader.setBounds(-220, 0, 2140, 50);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(198, 800));

        pScrollPane.setBackground(new java.awt.Color(0, 0, 0));
        pScrollPane.setPreferredSize(new java.awt.Dimension(198, 1200));
        pScrollPane.setLayout(null);

        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang1.png"))); // NOI18N
        jlbMenuBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbMenuBanHangMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbMenuBanHang);
        jlbMenuBanHang.setBounds(0, 0, 200, 70);

        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang1.png"))); // NOI18N
        jlbNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbNhapHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbNhapHangMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbNhapHang);
        jlbNhapHang.setBounds(0, 70, 200, 70);

        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien1.png"))); // NOI18N
        jlbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbNhanVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbNhanVien);
        jlbNhanVien.setBounds(0, 140, 200, 70);

        jlbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang1.png"))); // NOI18N
        jlbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbKhachHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbKhachHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbKhachHangMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbKhachHang);
        jlbKhachHang.setBounds(0, 210, 200, 70);

        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon1.png"))); // NOI18N
        jlbMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbMonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbMonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbMonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbMonMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbMon);
        jlbMon.setBounds(0, 280, 200, 70);

        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong1.png"))); // NOI18N
        jlbLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbLuongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbLuongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbLuongMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbLuong);
        jlbLuong.setBounds(0, 350, 200, 70);

        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap1.png"))); // NOI18N
        jlbNhaCungCap.setToolTipText("");
        jlbNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbNhaCungCapMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbNhaCungCap);
        jlbNhaCungCap.setBounds(0, 420, 200, 70);

        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai1.png"))); // NOI18N
        jlbKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbKhuyenMaiMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbKhuyenMai);
        jlbKhuyenMai.setBounds(0, 490, 200, 70);

        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai1.png"))); // NOI18N
        jlbUuDai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbUuDaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbUuDaiMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbUuDai);
        jlbUuDai.setBounds(0, 560, 200, 70);

        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu1.png"))); // NOI18N
        jlbChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbChucVuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbChucVuMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbChucVu);
        jlbChucVu.setBounds(0, 630, 200, 70);

        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan1.png"))); // NOI18N
        jlbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTaiKhoanMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbTaiKhoan);
        jlbTaiKhoan.setBounds(0, 700, 200, 70);

        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp1.png"))); // NOI18N
        jlbQuanLyApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbQuanLyAppMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbQuanLyApp);
        jlbQuanLyApp.setBounds(0, 770, 200, 70);

        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue1.png"))); // NOI18N
        jlbTinhThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTinhThueMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTinhThueMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbTinhThue);
        jlbTinhThue.setBounds(0, 840, 200, 70);

        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang1.png"))); // NOI18N
        jlbTKBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTKBanHangMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbTKBanHang);
        jlbTKBanHang.setBounds(0, 910, 200, 70);

        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra1.png"))); // NOI18N
        jlbTKChiTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTKChiTraMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbTKChiTra);
        jlbTKChiTra.setBounds(0, 980, 200, 70);

        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu1.png"))); // NOI18N
        jlbTKDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbTKDoanhThuMouseReleased(evt);
            }
        });
        pScrollPane.add(jlbTKDoanhThu);
        jlbTKDoanhThu.setBounds(0, 1050, 200, 70);

        jScrollPane1.setViewportView(pScrollPane);

        pFrame.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 220, 1000);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        pFrame.add(jLabel2);
        jLabel2.setBounds(0, 0, 200, 1050);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Set onclick cho jlbClose(Đóng ứng dụng)
    private void jlbCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseReleased
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMouseReleased

    private void jlbCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMousePressed
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMousePressed

    private void jlbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseEntered
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMouseEntered

    private void jlbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseExited
        jlbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close1.png"))); // NOI18N
    }//GEN-LAST:event_jlbCloseMouseExited

    private void jlbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlbCloseMouseClicked
    
    //Set onclick cho jlbHiden(Ẩn xuống thanh tabkbar)
    private void jlbHidenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseReleased
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMouseReleased

    private void jlbHidenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMousePressed
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMousePressed

    private void jlbHidenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseEntered
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMouseEntered

    private void jlbHidenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseExited
        jlbHiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an1.png"))); // NOI18N
    }//GEN-LAST:event_jlbHidenMouseExited

    private void jlbHidenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHidenMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jlbHidenMouseClicked

    //Set onclick cho jlbMenuBanHang
    private void jlbMenuBanHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseReleased
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMouseReleased

    private void jlbMenuBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMousePressed
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMousePressed

    private void jlbMenuBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseExited
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang1.png"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMouseExited

    private void jlbMenuBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseEntered
        jlbMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/menubanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMenuBanHangMouseEntered

    private void jlbMenuBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuBanHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbMenuBanHangMouseClicked
    
    //Set onclick cho jlbBanHang
    private void jlbNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseClicked
        
    }//GEN-LAST:event_jlbNhapHangMouseClicked

    private void jlbNhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseEntered
       jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhapHangMouseEntered

    private void jlbNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseExited
        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang1.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhapHangMouseExited

    private void jlbNhapHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMousePressed
        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhapHangMousePressed

    private void jlbNhapHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhapHangMouseReleased
        jlbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhaphang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhapHangMouseReleased
    
    //Set onclick cho jlbNhanVien
    private void jlbNhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseReleased
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMouseReleased

    private void jlbNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMousePressed
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMousePressed

    private void jlbNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseEntered
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMouseEntered

    private void jlbNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseExited
        jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhanvien1.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhanVienMouseExited
    
    private void jlbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbNhanVienMouseClicked
    
    //Set onclick cho jlbKhachHang
    private void jlbKhachHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhachHangMouseReleased
        jlbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhachHangMouseReleased

    private void jlbKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhachHangMousePressed
        jlbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhachHangMousePressed

    private void jlbKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhachHangMouseEntered
        jlbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhachHangMouseEntered

    private void jlbKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhachHangMouseExited
        jlbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khachhang1.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhachHangMouseExited

    private void jlbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhachHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbKhachHangMouseClicked
    
    //Set onclick cho jlbMon
    private void jlbMonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseReleased
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMouseReleased

    private void jlbMonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMousePressed
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMousePressed

    private void jlbMonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseEntered
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon2.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMouseEntered

    private void jlbMonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseExited
        jlbMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/mon1.png"))); // NOI18N
    }//GEN-LAST:event_jlbMonMouseExited

    private void jlbMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbMonMouseClicked
    
    //Set onclick cho jlbLuong
    private void jlbLuongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseReleased
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong2.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMouseReleased

    private void jlbLuongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMousePressed
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong2.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMousePressed

    private void jlbLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseEntered
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong2.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMouseEntered

    private void jlbLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseExited
        jlbLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/luong1.png"))); // NOI18N
    }//GEN-LAST:event_jlbLuongMouseExited

    private void jlbLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLuongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbLuongMouseClicked
    
    //Set onclick cho jlbNhaCungCap
    private void jlbNhaCungCapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseReleased
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseReleased

    private void jlbNhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMousePressed
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMousePressed

    private void jlbNhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseEntered
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap2.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseEntered

    private void jlbNhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseExited
        jlbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/nhacungcap1.png"))); // NOI18N
    }//GEN-LAST:event_jlbNhaCungCapMouseExited

    private void jlbNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhaCungCapMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbNhaCungCapMouseClicked
    
    //Set onclick cho jlbKhuyenMai
    private void jlbKhuyenMaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseReleased
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMouseReleased

    private void jlbKhuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMousePressed
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMousePressed

    private void jlbKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseEntered
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMouseEntered

    private void jlbKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseExited
        jlbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/khuyenmai1.png"))); // NOI18N
    }//GEN-LAST:event_jlbKhuyenMaiMouseExited

    private void jlbKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbKhuyenMaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbKhuyenMaiMouseClicked
    
    //Set onclick cho jlbUuDai
    private void jlbUuDaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseReleased
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMouseReleased

    private void jlbUuDaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMousePressed
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMousePressed

    private void jlbUuDaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseEntered
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai2.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMouseEntered

    private void jlbUuDaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseExited
        jlbUuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/uudai1.png"))); // NOI18N
    }//GEN-LAST:event_jlbUuDaiMouseExited

    private void jlbUuDaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUuDaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbUuDaiMouseClicked
    
    //Set onclick cho jlbChucVu
    private void jlbChucVuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseReleased
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseReleased

    private void jlbChucVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMousePressed
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMousePressed

    private void jlbChucVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseEntered
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseEntered

    private void jlbChucVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseExited
        jlbChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/chucvu1.png"))); // NOI18N
    }//GEN-LAST:event_jlbChucVuMouseExited

    private void jlbChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbChucVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbChucVuMouseClicked
    
    //Set onclick cho jlbTaiKhoan
    private void jlbTaiKhoanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseReleased
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMouseReleased

    private void jlbTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMousePressed
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMousePressed

    private void jlbTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseEntered
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMouseEntered

    private void jlbTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseExited
        jlbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/taikhoan1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTaiKhoanMouseExited

    private void jlbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTaiKhoanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTaiKhoanMouseClicked
    
    //Set onclick cho jlbQuanLyApp
    private void jlbQuanLyAppMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseReleased
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp2.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMouseReleased

    private void jlbQuanLyAppMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMousePressed
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp2.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMousePressed

    private void jlbQuanLyAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseEntered
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp2.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMouseEntered

    private void jlbQuanLyAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseExited
        jlbQuanLyApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/quanlyapp1.png"))); // NOI18N
    }//GEN-LAST:event_jlbQuanLyAppMouseExited

    private void jlbQuanLyAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbQuanLyAppMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbQuanLyAppMouseClicked
    
    //Set onclick cho jlbTinhThue
    private void jlbTinhThueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseReleased
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMouseReleased

    private void jlbTinhThueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMousePressed
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMousePressed

    private void jlbTinhThueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseEntered
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMouseEntered

    private void jlbTinhThueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseExited
        jlbTinhThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/tinhthue1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTinhThueMouseExited

    private void jlbTinhThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTinhThueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTinhThueMouseClicked
    
    //Set onclick cho jlbTKBanHang
    private void jlbTKBanHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseReleased
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMouseReleased

    private void jlbTKBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMousePressed
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMousePressed

    private void jlbTKBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseEntered
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMouseEntered

    private void jlbTKBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseExited
        jlbTKBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKBanhang1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKBanHangMouseExited

    private void jlbTKBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKBanHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTKBanHangMouseClicked
    
    //Set onclick cho jlbTKBanHang
    private void jlbTKChiTraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseReleased
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMouseReleased

    private void jlbTKChiTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMousePressed
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMousePressed

    private void jlbTKChiTraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseEntered
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMouseEntered

    private void jlbTKChiTraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseExited
        jlbTKChiTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKChitra1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKChiTraMouseExited

    private void jlbTKChiTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKChiTraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTKChiTraMouseClicked
    
    //Set onclick cho jlbTKDoanhThu
    private void jlbTKDoanhThuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseReleased
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMouseReleased

    private void jlbTKDoanhThuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMousePressed
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMousePressed

    private void jlbTKDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseEntered
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu2.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMouseEntered

    private void jlbTKDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseExited
        jlbTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/TKDoanhthu1.png"))); // NOI18N
    }//GEN-LAST:event_jlbTKDoanhThuMouseExited

    private void jlbTKDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTKDoanhThuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTKDoanhThuMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblHeader;
    private javax.swing.JLabel jlbChucVu;
    private javax.swing.JLabel jlbClose;
    private javax.swing.JLabel jlbHiden;
    private javax.swing.JLabel jlbKhachHang;
    private javax.swing.JLabel jlbKhuyenMai;
    private javax.swing.JLabel jlbLuong;
    private javax.swing.JLabel jlbMenuBanHang;
    private javax.swing.JLabel jlbMon;
    private javax.swing.JLabel jlbNhaCungCap;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbNhapHang;
    private javax.swing.JLabel jlbQuanLyApp;
    private javax.swing.JLabel jlbTKBanHang;
    private javax.swing.JLabel jlbTKChiTra;
    private javax.swing.JLabel jlbTKDoanhThu;
    private javax.swing.JLabel jlbTaiKhoan;
    private javax.swing.JLabel jlbTinhThue;
    private javax.swing.JLabel jlbUuDai;
    private javax.swing.JPanel pFrame;
    private javax.swing.JPanel pScrollPane;
    // End of variables declaration//GEN-END:variables
}
